descriptor-schema-version: "2.17"
info:
  name: certbot-iox
  version: 0.1.0
  description: "Certbot IOx application for managing certificates"
app:
  cpuarch: x86_64
  resources:
    host_mounts:
      - target_mount: "/etc/letsencrypt/"
        description: "Certificate files in container"
        host_mount_path: "/bootflash/SHARED-IOX"
    network:
      - interface-name: eth0
        ports:
          tcp:
            - "80"
  startup:
    rootfs: rootfs.tar
    target: ["certbot-iox.sh"]
    workdir: /opt/certbot
  type: docker
