descriptor-schema-version: "2.17"
info:
  name: localhost/dnoles/certbot-iox
  version: latest
app:
  cpuarch: x86_64
  resources:
    host_mounts:
      - target_mount: "/etc/letsencrypt/"
        description: "Certificate files in container"
        host_mount_path: "/bootflash/SHARED-IOX"
    network:
      - interface-name: eth0
        ports:
          tcp:
            - "80"
  startup:
    rootfs: rootfs.tar
    target:
      - /usr/local/bin/post-deploy.sh
    workdir: /data
  type: docker
